useDotenv: true
service: multi-region-node-lambda-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: v1/api.handler
    events:
      - httpApi:
          path: /
          method: GET
